### ISSUE TITLE
Ability for other users to give other users rewards as well

### ISSUE THREAD

**Issue by FaizanZahid** [NicolasSiver/nodebb-plugin-ns-awards#17]
I was just wondering this is a great plugin but right now I see a restriction that only admin can give them badges to the other uses since admin is probably one and it has limited creativity and number of good rewards to give...

 I was just thinking if other users can start giving rewards to their friends or followers on the phone then that would be awesome and because other users can define any name of the reward.. so they don't have necessarily to be pre define every time by admin...

Rewards can be named anything by other users. 

Can we add this thing in this plugin so that it also has admin rewards and also the user rewards

**Comment by NicolasSiver** [comment]
It's an idea. But it would be a different plugin. Since this plugin design about a controlled flow of rewards.

NS Awards plugin is quite powerful. It provides API. But Awards should be created in ACP.

**Comment by FaizanZahid** [comment]
Totally agree with the fact its very powerful. Great contribution.. Yes let's hope if user created awards r also done by another plugin or by an extra added feature in this one.
