### ISSUE TITLE
Some times the management does not show rewards even if the reward is given

### ISSUE THREAD

**Issue by FaizanZahid** [NicolasSiver/nodebb-plugin-ns-awards#18]
As you can see below,

![image](https://user-images.githubusercontent.com/9073066/40303077-43fb4564-5ce9-11e8-970c-74d2360a96a2.png)

admin has given award to this user and even his awards show on /awards page, but in ACP when i type this user, it says no award given to this user.

i have tested this with multiple users and awards, still same issue.

As you can see in log this user has been awarded before but it does not show in ACP management:
![image](https://user-images.githubusercontent.com/9073066/40303137-804f01cc-5ce9-11e8-9bd9-c3bb709f9e50.png)

**Comment by ic3fresh** [comment]
To precise. I think it does not work when person gets his 1st award. If you give same person next award everything will be OK.
Let's assume that you give award to person - in /awards it will be shown near the award but in "management" in ACP and in profile it does not (when you put in partial into theme). Next award given is seen everywhere.

**Comment by mdorda** [comment]
Workaround. The `-1` value is not handled in a source code. So if you are trying to get award list from database (https://github.com/NicolasSiver/nodebb-plugin-ns-awards/blob/master/plugin/database.js#L228) with limit `-1` it will return you all results except the last one. You can make pull request with handling `-1` value or just change in plugin settings **Max Rewards Per Account** field to for example `3`.

**Comment by NicolasSiver** [comment]
@mdorda thank you for the pointing into the issue with a limit.
