### ISSUE TITLE
Awards on profile pages are only showing for 1 user and not others, and best dimensions for images?

### ISSUE THREAD

**Issue by FaizanZahid** [NicolasSiver/nodebb-plugin-ns-awards#19]
I have followed your exact steps to add the partial to profile.tpl, but for some reason only awards are being shown for this user profile 

https://chatrooms.talkwithstranger.com/user/willow

but as u can see other users also have awards but they are not rendering on their profile view

https://chatrooms.talkwithstranger.com/awards

e.g this user https://chatrooms.talkwithstranger.com/user/layla

Also, what should be the exact dimensions for the awards  images so that they appear 100% responsive and perfect on all screens on topic view ,profile view and awards view, in our case it seems distorted, see please

![image](https://user-images.githubusercontent.com/9073066/40589689-d1dae696-61e9-11e8-97d9-1c2f485a278a.png)

**Comment by FaizanZahid** [comment]
here is what user is saying and this might be a bug,

![image](https://user-images.githubusercontent.com/9073066/40591964-5c32f938-6211-11e8-963f-a91a4f596b66.png)

**Comment by mdorda** [comment]
Workaround. The `-1` value is not handled in a source code. So if you are trying to get award list from database (https://github.com/NicolasSiver/nodebb-plugin-ns-awards/blob/master/plugin/database.js#L228) with limit `-1` it will return you all results except the last one. You can make pull request with handling `-1` value or just change in plugin settings **Max Rewards Per Account** field to for example `3`.
