### ISSUE TITLE
Allow the tooltip to show when tap on award icon on profile or topic view

### ISSUE THREAD

**Issue by FaizanZahid** [NicolasSiver/nodebb-plugin-ns-awards#20]
This is just an enhancement feature:

On mobile users don't know what each award title is by just looking at the icon, and the tool tip on mobile does not show. it should show on profile and post view if user taps on icon on mobile.

and i also think tapping the award icon should take users to /awards page

**Comment by NicolasSiver** [comment]
Here is an example of the template which is provided with a plugin: https://github.com/NicolasSiver/nodebb-plugin-ns-awards/blob/master/public/templates/partials/awards_topic.tpl

You can build your own template with any possible change to suffice your community.
