### ISSUE TITLE
Feature request: Make API accessible from 3rd party application

### ISSUE THREAD

**Issue by mdorda** [NicolasSiver/nodebb-plugin-ns-awards#25]
There are 2 API endpoints accessible from server side hooks:
- `filter:ns.awards.getAwards`
- `static:ns.awards.rewardUser`

It would be great to make these endpoints accessible from 3rd party application using URLs. There is a great plugin [nodebb-plugin-write-api](https://github.com/NodeBB/nodebb-plugin-write-api) which provides this functionality via its hook (https://github.com/NodeBB/nodebb-plugin-write-api/blob/master/routes/v2/index.js#L44-L58).

So everything what is need to do is to create URLs for awards endpoints:

```js
{
    bindRoutes: function(params, callback) {
        var router = params.router;
        var apiMiddleware = params.apiMiddleware;

        router.post(
            '/plugins/ns-awards/get-awards',
            apiMiddleware.requireUser,
            function(req, res) {
                api.getAwards(
                    req.body,
                    function(_, payload) {
                        res.send(payload);
                    }
                )
            }
        );

        router.post(
            '/plugins/ns-awards/reward-user',
            apiMiddleware.requireUser,
            function(req, res) {
                api.rewardUser(
                    req.body,
                    function(_, payload) {
                        res.send(payload);
                    }
                )
            }
        );

        callback(null, {
            router: router
        });
    },
},
```

and registr the method to `nodebb-plugin-write-api` using **plugin.json**

```json
{
    "hook": "filter:plugin.write-api.routes",
    "method": "hooks.writeApi.bindRoutes"
}
```

**Pros**:
- `nodebb-plugin-write-api` has already secured its API using baerer token (but it is not in conflict with awards security - it can be double secured)
- API endpoints are accessible via `/api/v2/plugins/ns-awards/get-awards` and `/api/v2/plugins/ns-awards/reward-user`
- in case any user does not have the `nodebb-plugin-write-api` plugin, nothing changed and everything works

Can I make pull request? Are you OK with adding this functionality?

**Comment by NicolasSiver** [comment]
Hello @mdorda 

The plugin was designed to work with hooks. It's overall nature of plugins and how they are working in NodeBB.

I think better will be if you create a small plugin which interacts with Awards via hooks and exposes API via HTTP. You will have full control of how HTTP endpoints should look like, and it will be up to you if you see a value to share it.

Regards
