### ISSUE TITLE
Error when uploading Images for Awards

### ISSUE THREAD

**Issue by MotherShip808** [NicolasSiver/nodebb-plugin-ns-awards#38]
Hi there, I am running into this isssue when I am trying to create an award.

`Error did occur: {"errno":-2,"code":"ENOENT","syscall":"copyfile","path":"/var/www/nodebb/node_modules/nodebb-plugin-ns-awards/public/uploads/award-467905ec-46c8-4643-85eb-69bfb01e5b62.png","dest":"/var/www/nodebb/public/uploads/awards/award-467905ec-46c8-4643-85eb-69bfb01e5b62.png"}`

It might be something wrong with my VPS setup, however I am not sure how to solve it and figured I should ask for some assistance.

**Comment by NicolasSiver** [comment]
It's possible that there are no rights to write the file.
Try to check the write rights for the user who runs NodeBB for both folders:

- `/var/www/nodebb/public/uploads/awards/`
- `/var/www/nodebb/node_modules/nodebb-plugin-ns-awards/public/uploads/`

**Comment by MotherShip808** [comment]
I was able to fix it by creating the /var/www/nodebb/public/uploads/awards/  directory.
