### ISSUE TITLE
auto-complete component make user who has a short name(length<3) can't get awards

### ISSUE THREAD

**Issue by gogoout** [NicolasSiver/nodebb-plugin-ns-awards#4]
the problem is caused by these code 

`client/acp/components/Autocomplete.react.js`

``` js
 _validateInput: function () {
        if (this.state.inputText.length >= 3) {
            this.props.valueDidChange(this.state.inputText);
        }
    }
```

I understand that userName.length>3 is common in english world. But in other language (such as chinese) is not that common.

do you need me to make a PR to fix this?

**Comment by NicolasSiver** [comment]
How many letters in username do you allow on your forum?

**Comment by gogoout** [comment]
2 letters is allowed and it's really common.
