### ISSUE TITLE
awards_topic template is empty

### ISSUE THREAD

**Issue by KNocTis** [NicolasSiver/nodebb-plugin-ns-awards#41]
NodeBB Version: v1.13.4-5

### **Issue:**

I followed README and insert this line into `post.tpl` file
```
	<!-- IMPORT partials/awards_topic.tpl -->
```
The topic page has only an empty `<div>` element with class "ns-awards-topic", event though `posts[n].nsRewards` has items inside.

### **Fix:**
Modify awards_topic.tpl file: 
`<!-- BEGIN nsRewards -->` --> `<!-- BEGIN posts.nsRewards -->` & `<!-- END nsRewards -->` -> `<!-- END posts.nsRewards -->`
The original code may be valid for old version of benchpressjs?

```
<!-- IF posts.nsRewards.length -->
<div class="ns-awards-topic">
    <!-- BEGIN posts.nsRewards -->
    <div class="ns-awards-topic__item">
        <img class="ns-awards-topic__image teaser-pic img-responsive" src="{posts.nsRewards.award.url}" alt="{posts.nsRewards.award.name}" title="{posts.nsRewards.award.name}"
             data-toggle="awards-tooltip" data-placement="top" data-original-title="{posts.nsRewards.award.name}" />
    </div>
    <!-- END posts.nsRewards -->
</div>
<!-- ENDIF posts.nsRewards.length -->
```

**Comment by NicolasSiver** [comment]
In order to enrich data with awards, you need to activate this feature in settings. Hopefully, there is no regression in the latest version v7 for NodeBB v2.2.x. Try and let me know. Feel free to open a new issue and link this one.
