### ISSUE TITLE
Can't upload Awards Picture 

### ISSUE THREAD

**Issue by LJeremy** [NicolasSiver/nodebb-plugin-ns-awards#7]
Hi,

I am using NodeBB 0.9.3 and nodebb-plugin-ns-awards 2.1.0, I am hosting the forum on a subfolder, my url looks like this: https://example.com/forum/.

The ACP works, however when I try to upload a picture for the award It gets 404'ed.
`POST https://example.com/api/admin/plugins/awards/images 404 (Not Found)`

It posts to the wrong URL, or atleast that is what I think. I tried changing it in the plugin/index.js using both the pluginUri and apiUri, both with no result.

Is this because of the way the forum is set up using a subfolder? Or is it because it doesn't support it?
I think the problem is on my behalf and not a problem with the plugin.

**Comment by NicolasSiver** [comment]
It could be a reason. 
To have forum in subfolder, plugin should handle relative paths. 
I didn't implemented just behavior.
