### ISSUE TITLE
Where i need to put the template codes?

### ISSUE THREAD

**Issue by Nisthar** [NicolasSiver/nodebb-plugin-ns-awards#8]
I put the  in /node_modules/nodebb-theme-persona/templates/partials/topic/post.tpl after the line for . But its CSS are not correct when i reloaded the forum. Its overlapping with some content of the topic and the label showing the time of the topic is misaligned due to it? Where do i need to add the code  to work without changing anything else?

**Comment by NicolasSiver** [comment]
In my theme, I have placed code in the end of user related block:

```
<div class="post-user">
       ...

        <!-- IMPORT partials/awards_topic.tpl -->
</div>
```

Does it work for you?
Also, via ACP, you can override CSS: https://github.com/NicolasSiver/nodebb-plugin-ns-awards/blob/master/style/topic.less

**Comment by Nisthar** [comment]
@NicolasSiver Sorry, Could you tell me where would it be exactly? Because i can't find a div with class post-user. 

I tried to place the awards in various places in topic view. But it breaks the css.

**Comment by NicolasSiver** [comment]
Try to place it after `a` tag here, do you still have issues with layout?

https://github.com/NodeBB/nodebb-theme-persona/blob/master/templates/partials/topic/post.tpl#L11

**Comment by Nisthar** [comment]
@NicolasSiver This is just a CSS question. But i can't place it correctly. Anyway to display it vertically without changing other styles?

Currently, I see that the post content gets slightly changed because of adding the awards. 

I think it should be nice if we can place the awards vertically below the user image ( each award in a new line)

**Comment by NicolasSiver** [comment]
Maybe your theme isn't designed for such change.

**Comment by Nisthar** [comment]
@NicolasSiver I am using persona.

**Comment by NicolasSiver** [comment]
Yes, Persona isn't good fit for it, if you want awards in posts.

Here is an example, how I have changed Persona (plugins, template editing):

<img width="1152" alt="screen shot 2016-03-17 at 3 18 45 pm" src="https://cloud.githubusercontent.com/assets/135263/13858146/b1195e14-ec53-11e5-8910-299913661640.png">

**Comment by Nisthar** [comment]
@NicolasSiver Its nice. But what happens if there are two or more awards?

**Comment by NicolasSiver** [comment]
On the screen, there are 2 awards. If it will be more than 2, they will start on next line. So it will look like 2 columns basically.

**Comment by Nisthar** [comment]
@NicolasSiver It would be nice if you could tell me or post a guide for persona theme. Because showing awards in the post is a common thing in other forum. Only nodebb doesn't had it until now :+1:
