### ISSUE TITLE
When creating award, add button is disabled.

### ISSUE THREAD

**Issue by spideynn** [NicolasSiver/nodebb-plugin-ns-awards#9]
On NodeBB 1.0.0, when I go to create an award, the add award button is disabled even though all the fields are filled out, and clicking it does nothing. 
![error](https://cloud.githubusercontent.com/assets/1433970/13820470/ddb5e838-eb73-11e5-9e38-34cd969c45c2.png)

**Comment by NicolasSiver** [comment]
Another reason could be, that upload of the image wasn't successful.
Or it could be just a bug, I will double check.

**Comment by NicolasSiver** [comment]
@spideynn 
1. In Chrome, check Network Tab in Developer Tools (View -> Developer -> Developer Tools).
2. Open Network tab
3. Now add image
4. Check http request for `/api/admin/plugins/awards/images` - is Status Code `200 OK` ?

**Comment by spideynn** [comment]
I use Apache to rewrite the urls for my web server, and I found out that I never wrote a `ProxyPass` for the `/api/` route, and its working now. Thanks!
